---
apiVersion: v1
kind: Service
metadata:
  name: kubenav
  namespace: kubenav
spec:
  type: ClusterIP
  ports:
    - port: 14122
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kubenav
